### ISSUE TITLE
__init__() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by gkeeth** [svg2mod/svg2mod#13]
Running svg2mod on an svg that can't be cleanly converted results in `__init__() got an unexpected keyword argument 'verbose'`

```
$ svg2mod -i frontpanel.svg -p 1.0
Parsing SVG...
No handler for element {http://www.w3.org/2000/svg}metadata
No handler for element {http://www.w3.org/2000/svg}defs
No handler for element {http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}namedview
No handler for element {http://www.w3.org/2000/svg}title
No handler for element {http://www.w3.org/2000/svg}desc
transform: translate [0.0, 0.0]
transform: scale [1.0, 1.0]
Traceback (most recent call last):
  File "/usr/bin/svg2mod", line 33, in <module>
    sys.exit(load_entry_point('svg2mod===0.1.3-2-g4be236f', 'console_scripts', 'svg2mod')())
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 35, in main
    imported = Svg2ModImport(
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 479, in __init__
    self.svg = svg.parse( file_name, verbose_print )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg/svg/__init__.py", line 6, in parse
    f = svg.Svg(filename, verbose)
  File "/usr/lib/python3.8/site-packages/svg2mod/svg/svg/svg.py", line 212, in __init__
    self.parse(filename)
  File "/usr/lib/python3.8/site-packages/svg2mod/svg/svg/svg.py", line 241, in parse
    top_group.append(self.root)
  File "/usr/lib/python3.8/site-packages/svg2mod/svg/svg/svg.py", line 303, in append
    item.append(elt)
  File "/usr/lib/python3.8/site-packages/svg2mod/svg/svg/svg.py", line 292, in append
    item = elt_class(elt, verbose=self.verbose)
TypeError: __init__() got an unexpected keyword argument 'verbose'
```
If I run on an empty svg (converts cleanly), then I get no error so I think this issue may only pop up when the svg will not convert cleanly. Adding the `--verbose` flag makes no difference; I get the same error either way.

The specific svg I'm using is attached (zipped so github will accept it). I was in the process of editing it to convert cleanly when I ran into this issue.

[frontpanel.zip](https://github.com/svg2mod/svg2mod/files/5419820/frontpanel.zip)

Thanks!

**Comment by Sodium-Hydrogen** [comment]
I found the issue with the svg parser. I had missed adding the verbose flag to the circle element because its class inherits from the ellipse class instead of the base class. I will be rolling a fix to update this soon.

I am looking into adding support for inkscape objects because they are currently unsupported. If you convert everything in the F.Fab layer into paths it should parse just fine.

**Comment by gkeeth** [comment]
Great, thanks for the quick response!

**Comment by Sodium-Hydrogen** [comment]
Related to the file you gave me. Stroke widths are not being scaled to match the scaling of the points since the file you gave has a non-standard scaling so I'm adding that to this issue to get sorted out.

**Comment by gkeeth** [comment]
Interesting, thanks for looking into it. This file started life as a kicad SVG export of an edge cuts layer, so that must be where the weird scaling comes from (I didn’t intentionally change it). 

I also started working on this with an older version of svg2mod so there’s possibly some weird stuff in the file I did to try and work around older bugs (weird shape widths and spurious extra polygons). If I notice any issues going forward I’ll try to report them. 

I also don’t really know how to use Inkscape, so I’m sure I’m breaking the plugin in all sorts of weird ways.

**Comment by Sodium-Hydrogen** [comment]
This is very useful because I know how to work svg2mod so I wouldn't think of testing some of the things that it is getting stuck on.

I am trying to make it as resilient as possible so it just works without fiddling. I have been talking to the maintainer of svg2shenzhen which was supposed to be a replacement for this tool because it had lost support by the original maintainer. But now that it is getting updated again and all the weird bugs are getting fixed we are going to try to integrate this tool back into svg2shenzhen. So I would definitely appreciate anything you find that isn't working or any features you would like.

**Comment by gkeeth** [comment]
Great, I’ll definitely report any issues I run into.

**Comment by gkeeth** [comment]
just confirming -- the fix worked perfectly, thanks. Circles being converted automatically is also really helpful.
