### ISSUE TITLE
Cannot convert svg file

### ISSUE THREAD

**Issue by shlane** [svg2mod/svg2mod#49]
### The problem

When I try to run your sample I get the following error:
ImportError: cannot import name 'svg' from partially initialized module 'svg2mod' (most likely due to a circular import)

I am running windows 10 and python 3.10 and did the pip install of version 1.1
As a test I have copied the svg2mod.svg sample file to the svg2mod-main\svg2mod folder

 In the windows command prompt after changing the current directory to the svg2mod-main\svg2mod folder 

I type

python svg2mod.py -i svg2mod.svg -o test.pretty/test

I have tried other svg files and get the same error message.  What am I doing wrong?

### Version

1.1

### Command line

python svg2mod.py -i svg2mod.svg -o test.pretty/test

### Debug output

```txt
D:\WinDocs\UPenn\Research\Vet School\Sensor Mounts\svg2mod-main\svg2mod>python svg2mod.py -i svg2mod.svg -o test.pretty/test
Traceback (most recent call last):
  File "D:\WinDocs\UPenn\Research\Vet School\Sensor Mounts\svg2mod-main\svg2mod\svg2mod.py", line 25, in <module>
    from svg2mod import svg
  File "D:\WinDocs\UPenn\Research\Vet School\Sensor Mounts\svg2mod-main\svg2mod\svg2mod.py", line 25, in <module>
    from svg2mod import svg
ImportError: cannot import name 'svg' from partially initialized module 'svg2mod' (most likely due to a circular import) (D:\WinDocs\UPenn\Research\Vet School\Sensor Mounts\svg2mod-main\svg2mod\svg2mod.py)
```

### Sample file and additional information

I am using the svg2mod.svg file

**Comment by Sodium-Hydrogen** [comment]
This application is intended to be installed with pip which contains directions on how to execute it.

Once you install it via pip you don't need to call python to use it so the command line would be:
```
svg2mod -i svg2mod.svg -o test.pretty/test
```
instead of
```
python svg2mod.py -i svg2mod.svg -o test.pretty/test
```

If this doesn't work then you will need to follow the instructions on [this post](https://stackoverflow.com/questions/36092388/adding-installed-pip-package-to-path-automatically) to fix your python installation on windows.
